<?php
/**
 * Options de conception des cuves (export production 30.09.2026)
 * Appliqué seulement si la table est vide (voir seed() de l'installateur).
 */
defined('ABSPATH') || exit;

return [
    ['Id' => 1, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'AISI316L', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 2, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'S235JR', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 3, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'AISI304L', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 4, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Energy accumulator', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 5, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Sanitary accumulator', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 6, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Cold water tank', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 7, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Chilled water tank', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 8, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Water heater', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 9, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Pressure relief bottle', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 10, 'SelectType' => 'support', 'articleId' => 0, 'Value' => 'feet', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 11, 'SelectType' => 'support', 'articleId' => 0, 'Value' => 'ring', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 12, 'SelectType' => 'connection', 'articleId' => 0, 'Value' => 'threaded fitting', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 3],
    ['Id' => 13, 'SelectType' => 'connection', 'articleId' => 0, 'Value' => 'flange', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 2],
    ['Id' => 14, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'bend pipe', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 15, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'loading spray tube', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 16, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'baffle plate', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 17, 'SelectType' => 'accessories', 'articleId' => 10, 'Value' => 'pour thermomètre, 0-120° C, L=200, D=100', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 18, 'SelectType' => 'accessories', 'articleId' => 13, 'Value' => 'pour sonde(s) sans ces dernière(s) avec doigt(s) de gant', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 21, 'SelectType' => 'registre', 'articleId' => 0, 'Value' => 'Heat exchanger', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 22, 'SelectType' => 'DrilledPlate', 'articleId' => 0, 'Value' => 'drilled plate (35%)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 23, 'SelectType' => 'welding', 'articleId' => 0, 'Value' => 'Welding', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 24, 'SelectType' => 'connection', 'articleId' => 0, 'Value' => 'revision flange', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 1],
    ['Id' => 25, 'SelectType' => 'insulationType', 'articleId' => 0, 'Value' => 'rockwool insulation', 'is_supplier_delivery' => 0, 'matiere' => 'Laine de roche', 'image' => 0, 'sort' => 0],
    ['Id' => 26, 'SelectType' => 'insulationType', 'articleId' => 0, 'Value' => 'polyester fiber fleece with polystyrene jacket', 'is_supplier_delivery' => 1, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 28, 'SelectType' => 'insulationType', 'articleId' => 0, 'Value' => 'Armaflex', 'is_supplier_delivery' => 0, 'matiere' => 'Armaflex', 'image' => 0, 'sort' => 0],
    ['Id' => 29, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '19', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 30, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '25', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 31, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '32', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 32, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '50', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 33, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '100', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 34, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '130', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 35, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '160', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 36, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '200', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 37, 'SelectType' => 'accessories', 'articleId' => 8, 'Value' => 'pour thermomètre, -20 +40° C, L=200, D=100', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 38, 'SelectType' => 'accessories', 'articleId' => 563, 'Value' => 'flange adapter Ø400/480 -> Ø120/180', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 39, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '120', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 40, 'SelectType' => 'accessories', 'articleId' => 566, 'Value' => 'flange adapter Ø400/480 -> Ø200/280', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 41, 'SelectType' => 'not used', 'articleId' => 0, 'Value' => 'PIR', 'is_supplier_delivery' => 1, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 42, 'SelectType' => 'insulationType', 'articleId' => 0, 'Value' => 'NEODUL', 'is_supplier_delivery' => 1, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 43, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Collector', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 44, 'SelectType' => 'typ', 'articleId' => 0, 'Value' => 'Horizontal energy accumulator', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 45, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '64', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 46, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'pour thermomètre(s) sans ce(s) dernier(s)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 47, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'pour sonde(s) sans ces dernière(s)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 48, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '110', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 49, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'bend pipe with conical flow diffuser', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 50, 'SelectType' => 'insulationThickness', 'articleId' => 0, 'Value' => '75', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 51, 'SelectType' => 'insulationCover', 'articleId' => 0, 'Value' => 'with Stucco sheet metal coat', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 52, 'SelectType' => '', 'articleId' => 0, 'Value' => 'with Inox sheet metal coat', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 53, 'SelectType' => 'insulationCover', 'articleId' => 0, 'Value' => 'without coat', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 54, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'enamel-coated steel', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 55, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'P355GH', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 56, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'U-Type Stratified (L = 175mm)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 57, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'U-Type Stratified (L = 590mm)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 58, 'SelectType' => 'accessories', 'articleId' => 0, 'Value' => 'U-Type Stratified (L = 700mm)', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
    ['Id' => 59, 'SelectType' => 'material', 'articleId' => 0, 'Value' => 'P365GH', 'is_supplier_delivery' => 0, 'matiere' => '', 'image' => 0, 'sort' => 0],
];
